### ISSUE TITLE
Connection state is not immediately updated when going back to the list view

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/integration-settings#29]
The ActiveCampaign connection was disabled in the previous step

<img width="1792" alt="Screenshot 2021-04-15 at 04 34 24" src="https://user-images.githubusercontent.com/1112129/114806276-c594e900-9da4-11eb-8391-a70797bb5641.png">

**Comment by jakeprins** [comment]
Tested it locally but can not reproduce it. Are there any special circumstances when this happens?

**Comment by Gdewilde** [comment]
Needs further investigation to reproduce
