### ISSUE TITLE
Logs view

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/integration-settings#46]
Give consumers full visibility in the calls triggered by integrations. Needs to help create visibility when certain calls are failing. 

Goal: offload support questions and provide data transparency 

Filter out Vault calls

**Comment by jakeprins** [comment]
The idea was the only show the logs if a certain property is set when creating the session, right?

**Comment by Gdewilde** [comment]
Correct. At first, I was thinking about only hiding logs if the following is provided
```
settings: {
	showLogs: false
}
```
