### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/integration-settings#50]
Add search functionality to quickly discover which integrations are available (the search extends to all connections across all APIs, e.g., Salesforce will appear twice once linked to CRM and once linked to lead). Check mockup used for the landing page (search box only).

Research if we can re-use search elements from our other repos like Ecosystem and the Dev docs

**Comment by jakeprins** [comment]
What happens if you select a result?

**Comment by Gdewilde** [comment]
Navigate to connection view

**Comment by jakeprins** [comment]
That page with the connector form? A connection should first be created right?

**Comment by Gdewilde** [comment]
Yes and the creation should happen in the background if it not already exists. Check if that UX makes sense

**Comment by jakeprins** [comment]
We should then also enable the unified API for that connection right? Looks like this is currently only possible in the app?

**Comment by Gdewilde** [comment]
@jakeprins we should add a loading state to the search while it's loading when entering the session
