### ISSUE TITLE
Checkbox fields only need to be marked required if required

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/integration-settings#7]
<img width="734" alt="Screenshot 2021-03-16 at 03 49 56" src="https://user-images.githubusercontent.com/1112129/111248722-bfc3b080-860a-11eb-8350-fb67512cd4cc.png">

**Comment by jakeprins** [comment]
Isn't this a required checkbox? In this example `required: true` is returned from the API 

![CleanShot 2021-03-16 at 09 19 01](https://user-images.githubusercontent.com/17762366/111277366-ab96a800-8638-11eb-9cbc-bfcd986baa93.png)

**Comment by Gdewilde** [comment]
Can we disable the required attribute for checkboxes in the UI?

/cc@Nick Lloyd as far I know a checkbox can't be made required in SF. 






On Tue, Mar 16, 2021 9:23 AM, Jake Prins ***@***.***  wrote:


Isn't this a required checkbox? In this example required: true  is returned from
the API



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



—Gertjan De WildeCEO & Co-founder+ 32 (0) 497 20 60 51Apideck - Take your
platform strategy to the next level

**Comment by jakeprins** [comment]
Only when the API returns `required: true` we mark it as required. @nicklloyd any ideas?
![CleanShot 2021-03-16 at 10 14 39](https://user-images.githubusercontent.com/17762366/111284489-755d2680-8640-11eb-8c86-82a17c8922d7.png)
